<?xml version="1.0" ?>
<robot name="noovelia_forklift"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find forklift_description)/urdf/material.xacro" />

  <!--#### various constants ####-->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="M_PI_4" value="0.785" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!--#### back/carrosserie LIFT properties ####-->
  <xacro:property name= "carrosserie_lift_width" value="1.2" />
  <xacro:property name= "carrosserie_lift_length" value="0.7" />
  <xacro:property name= "carrosserie_lift_height" value="1.1" />
  <xacro:property name= "carrosserie_lift_mass" value="35" />
  <!-- Offset between link and lift mesh for proper placement-->
  <xacro:property name= "carrosserie_lift_z_offset" value="0.065" />
  <xacro:property name= "carrosserie_lift_x_offset" value="1.24" />

  <!--#### LIFT chassis/base fork properties ####-->
  <xacro:property name= "chassis_mass" value="40" />
  <xacro:property name= "chassis_x_offset" value="0.93" />
  <xacro:property name= "chassis_y_offset" value="1.24" />
  <xacro:property name= "chassis_z_offset" value="0.28" />

  <!--#### main wheel properties that performs steer + move ####-->
  <xacro:property name="wheel_width" value="0.08" />
  <xacro:property name="wheel_radius" value="0.12" />
  <xacro:property name="wheel_mass" value="10" />
  <!-- in kg-->
  <xacro:property name="wheel_x_offset" value="1.7" />
  <!-- in kg-->

  <!--#### Navigation Laser properties ####-->
  <xacro:property name="laser_mass" value="0.01"/>
  <xacro:property name="laser_length" value="0.08"/>
  <xacro:property name="laser_width" value="0.07"/>
  <xacro:property name="laser_height" value="0.06"/>
  <xacro:property name="laser_offset_z" value="${laser_height/2}"/>

  <!--### caster/fixed wheel properties ####-->
  <xacro:property name="caster_radius" value="0.08" />
  <xacro:property name="caster_length" value="0.16" />
  <xacro:property name="caster_y_offset" value="0.52" />

  <!--#### Intertia Elements of various objects and shapes ####-->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0" iyy="${m*(x*x+z*z)/12}" iyz = "0" izz="${m*(x*x+z*z)/12}" />
  </xacro:macro>

  <!--#### Links and Joints of Forklift ####-->
  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${caster_radius}" rpy="0 0 0" />
    <child link="base_link" />
    <parent link="base_footprint"/>
  </joint>

  <link name="base_link">
    <collision name="base_link_collision">
      <origin rpy="${M_PI_2} 0 ${M_PI_2}" xyz="${carrosserie_lift_x_offset} 
                  -${carrosserie_lift_width/2} 
                  -${carrosserie_lift_z_offset}"/>
      <geometry>
        <mesh filename="package://forklift_description/meshes/Forklift model/carrosserie lift.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <visual name="base_link_visual">
      <origin rpy="${M_PI_2} 0 ${M_PI_2}" xyz="${carrosserie_lift_x_offset}  
                  -${carrosserie_lift_width/2} 
                  -${carrosserie_lift_z_offset}"/>
      <geometry>
        <mesh filename="package://forklift_description/meshes/Forklift model/carrosserie lift.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="${carrosserie_lift_mass}" />
      <origin xyz="${carrosserie_lift_x_offset + carrosserie_lift_length/2} 
                   0 
                   0.1" rpy="0 0 0"/>
      <xacro:box_inertia m="${carrosserie_lift_mass}" x="${carrosserie_lift_width}" y="${carrosserie_lift_length}" z="${carrosserie_lift_height}"/>
    </inertial>
  </link>

  <joint name="fork_joint" type="fixed">
    <origin xyz="0.18 0.0 0.0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_fork"/>
  </joint>

  <link name="base_fork">
    <collision name="fork_collision">
      <origin rpy="${M_PI_2} 0 ${M_PI_2}" xyz="-${chassis_x_offset} 
                   -${chassis_y_offset} 
                   -${chassis_z_offset}"/>
      <geometry>
        <mesh filename="package://forklift_description/meshes/Forklift model/chassis AGV FL.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <visual name="fork_visual">
      <origin rpy="${M_PI_2} 0 ${M_PI_2}" xyz="-${chassis_x_offset} 
                   -${chassis_y_offset} 
                   -${chassis_z_offset}"/>
      <geometry>
        <mesh filename="package://forklift_description/meshes/Forklift model/chassis AGV FL.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 
                   0 
                   0.2"/>
      <mass value="${chassis_mass}" />
      <inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.08" iyz="0.0" izz="0.08" />
    </inertial>
  </link>

  <link name="fixed_left_wheel_link">
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      <origin/>
    </inertial>
    <visual name="fixed_left_wheel_visual">
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${caster_radius}" length="${caster_length}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision name="fixed_left_wheel_collision">
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${caster_radius}" length="${caster_length}" />
      </geometry>
      <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
    </collision>
  </link>

  <joint name="base2fixed_left_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="fixed_left_wheel_link"/>
    <origin xyz="0 ${caster_y_offset} 0" rpy="0 0 0" />
    <!-- <axis xyz="0 1 0" /> -->
  </joint>

  <link name="fixed_right_wheel_link">
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      <origin/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${caster_radius}" length="${caster_length}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${caster_radius}" length="${caster_length}" />
      </geometry>
      <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
    </collision>
  </link>

  <joint name="base2fixed_right_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="fixed_right_wheel_link"/>
    <origin xyz="0 -${caster_y_offset} 0" rpy="0 0 0" />
    <!-- <axis xyz="0 1 0" /> -->
  </joint>

  <link name="steer_link">
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      <origin/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.15 0.15 0.15" />
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <link name="sd_wheel_link">
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      <origin/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>

  <joint name="base2steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="steer_link"/>
    <limit effort="10000.0" lower="-${M_PI_2}" upper="${M_PI_2}" velocity="100"/>
    <origin xyz="${wheel_x_offset} 0 ${wheel_radius - caster_radius}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <joint name="steer2sd_wheel_joint" type="continuous">
    <parent link="steer_link"/>
    <child link="sd_wheel_link"/>
    <limit effort="10000.0" velocity="100"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!--#### Laser####-->
  <xacro:include filename="$(find forklift_description)/urdf/laser.xacro" />
  <xacro:laser name = "nav1" x_offset = "1.7" y_offset = "0.55" z_offset = "${laser_offset_z}"/>
  <xacro:laser name = "nav2" x_offset = "1.7" y_offset = "-0.55" z_offset = "${laser_offset_z}"/>
  <xacro:laser name = "nav3" x_offset = "0.5" y_offset = "0" z_offset = "${laser_offset_z}"/>

  <!--#### GAZEBO references ####-->
  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="base_fork">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="base_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="steer_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="fixed_left_wheel_link">
    <!-- <mu1 value="10000.0" />
    <mu2 value="10000.0" />
    <kp value="10000000000.0" />
    <kd value="1.0" /> -->
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="fixed_right_wheel_link">
    <!-- <mu1 value="10000.0" />
    <mu2 value="10000.0" />
    <kp value="10000000000.0" />
    <kd value="1.0" /> -->
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="sd_wheel_link">
    <mu1 value="10000.0" />
    <mu2 value="10000.0" />
    <kp value="10000000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <!--      <robotNamespace>/forklift</robotNamespace> -->
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="steer_drive_controller" filename="libgazebo_ros_steer_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100</updateRate>
      <steerJoint>base2steer_joint</steerJoint>
      <driveJoint>steer2sd_wheel_joint</driveJoint>
      <!-- <fixedWheelLeftJoint>base2fixed_left_wheel_joint</fixedWheelLeftJoint>
      <fixedWheelRightJoint>base2fixed_right_wheel_joint</fixedWheelRightJoint> -->
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <steeringFixWheelDistanceX>1.190</steeringFixWheelDistanceX>
      <steeringFixWheelDistanceY>0.0</steeringFixWheelDistanceY>
      <steerTorque>1000</steerTorque>
      <driveTorque>1000</driveTorque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>/odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <wheelAcceleration>0.5</wheelAcceleration>
      <odomEncSteeringAngleOffset>0.01</odomEncSteeringAngleOffset>
      <!--odometrySource>encoder</odometrySource-->
      <publishWheelJointState>true</publishWheelJointState>
      <!-- <publishWheelTF>true</publishWheelTF>  -->
    </plugin>
  </gazebo>
</robot>