<?xml version="1.0" ?>
<robot name="noovelia_forklift" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="M_PI_4" value="0.785" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!--the main wheel that perform steer + move behind the lift-->
  <xacro:property name="wheel_width" value="0.09" /> 
  <xacro:property name="wheel_radius" value="0.12" /> 
  <xacro:property name="wheel_mass" value="10" /> <!-- in kg-->

   <xacro:macro name="default_inertial" params="mass w h d yorigin">
    <inertial>
      <origin rpy="0 0 0" xyz="0 -${yorigin} ${h/2}"/>
      <mass value="${mass}" />
      <inertia ixx="${(1/12)*(h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*(w*w + d*d)}" iyz="0.0" izz="${(1/12)*(w*w + h*h)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" /> 
  </xacro:macro>

  <xacro:include filename="$(find forklift_description)/urdf/material.xacro" />

  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_fork origin -->
  <link name="base_footprint">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
  </link>>

<link name="base_fork">
    <collision name="fork_collision">
      <origin rpy="${M_PI_2} 0 0" xyz="-1.25 0.8 -0.2"/>
        <geometry>
            <mesh filename="package://forklift_description/meshes/Forklift model/chassis AGV FL.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <visual name="fork_visual">
      <origin rpy="${M_PI_2} 0 0" xyz="-1.25 0.8 -0.2"/>
      <geometry>
        <mesh filename="package://forklift_description/meshes/Forklift model/chassis AGV FL.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 -0.2 0.3"/>
      <mass value="40" />
    <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
</link>

<joint name="base_fork_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.25 0"/>
    <parent link="base_footprint"/>
    <child link="base_fork"/>
</joint>

 <link name="base_link">
    <collision name="base_link_collision">
      <origin rpy="${M_PI/2} 0 0" xyz="-0.6 -1.1 -${wheel_radius}"/>
        <geometry>
            <mesh filename="package://noovelia_robot_description/meshes/Forklift model/carrosserie lift.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <visual name="base_link_visual">
      <origin rpy="${M_PI/2} 0 0" xyz="-0.6 -1.1 -${wheel_radius}"/>
      <geometry>
        <mesh filename="package://noovelia_robot_description/meshes/Forklift model/carrosserie lift.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="red"/>
    </visual>
    <xacro:default_inertial mass="40" w = "1.1" h = "1.2" d = "0.9" yorigin = "1.6"/>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_fork"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}"/>
  </joint>

      <link name="steer_link">
        <inertial>
          <mass value="0.05"/>
          <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.16 0.16 0.16" />
          </geometry>
          <material name="orange"/>
        </visual>
      </link>
      
      <link name="sd_wheel_link">
        <inertial>
          <mass value="${wheel_mass}"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="${M_PI_2} 0 ${M_PI_2}" />
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}" />
          </geometry>
          <material name="black"/>
        </visual>
        
        <collision>
          <origin xyz="0 0 0" rpy="${M_PI_2} 0 ${M_PI_2}" />
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}" />
          </geometry>
        </collision>
      </link>

      <joint name="base2steer_joint" type="revolute">
        <parent link="base_link"/>
        <child link="steer_link"/>
        <limit effort="10000.0" lower="-${M_PI_2}" upper="${M_PI_2}" velocity="100"/>
        <origin xyz="0 -1.65 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
      </joint>

      <joint name="steer2sd_wheel_joint" type="continuous">
        <parent link="steer_link"/>
        <child link="sd_wheel_link"/>
        <limit effort="10000.0" velocity="100"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
      </joint>

      <link name="fixed_left_wheel_link">
        <inertial>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0.11 0" rpy="1.57 0 0" />
          <geometry>
            <mesh filename="package://noovelia_robot_description/meshes/Forklift model/Roues avant.STL" scale="0.001 0.001 0.001"/>
          </geometry>
          <material name="grey"/>
        </visual>
        
        <collision>
          <origin xyz="0 0.11 0" rpy="1.57 0 0" />
          <geometry>
            <mesh filename="package://noovelia_robot_description/meshes/Forklift model/Roues avant.STL" scale="0.001 0.001 0.001"/>
          </geometry>
         <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
        </collision>
      </link>
      
      <joint name="base2fixed_left_wheel_joint" type="fixed">
        <parent link="base_fork"/>
        <child link="fixed_left_wheel_link"/>
        <origin xyz="0.45 0.05 0.02" rpy="0 0 0" />
        <!-- <axis xyz="1 0 0" /> -->
      </joint>
      
      <link name="fixed_right_wheel_link">
        <inertial>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0.11 0" rpy="1.57 0 0" />
          <geometry>
            <mesh filename="package://noovelia_robot_description/meshes/Forklift model/Roues avant.STL" scale="0.001 0.001 0.001"/>
          </geometry>
          <material name="grey"/>
        </visual>
        <collision>
          <origin xyz="0 0.11 0" rpy="1.57 0 0" />
          <geometry>
            <mesh filename="package://noovelia_robot_description/meshes/Forklift model/Roues avant.STL" scale="0.001 0.001 0.001"/>
          </geometry>
         <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
        </collision>
      </link>

      <joint name="base2fixed_right_wheel_joint" type="fixed">
        <parent link="base_fork"/>
        <child link="fixed_right_wheel_link"/>
        <origin xyz="-0.6 0.05 0.02" rpy="0 0 0" />
        <!-- <axis xyz="1 0 0" /> -->
      </joint>

  <!--gazebo references-->
   <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="base_fork">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="base_link">
        <turnGravityOff>false</turnGravityOff>
        <material>Gazebo/Orange</material>
    </gazebo>


    <gazebo reference="steer_link">
      <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="fixed_left_wheel_link" >
      <!-- <mu1 value="10000.0" />
      <mu2 value="10000.0" />
      <kp  value="10000000000.0" />
      <kd  value="1.0" /> -->
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="fixed_right_wheel_link" >
      <!-- <mu1 value="10000.0" />
      <mu2 value="10000.0" />
      <kp  value="10000000000.0" />
      <kd  value="1.0" /> -->
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="sd_wheel_link" >
      <mu1 value="10000.0" />
      <mu2 value="10000.0" />
      <kp  value="10000000000.0" />
      <kd  value="1.0" />
    <material>Gazebo/Black</material>
  </gazebo>
     
      <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
<!--      <robotNamespace>/forklift</robotNamespace> -->
    </plugin>
  </gazebo>

   <gazebo>
    <plugin name="steer_drive_controller" filename="libgazebo_ros_steer_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100</updateRate>
      <steerJoint>base2steer_joint</steerJoint>
      <driveJoint>steer2sd_wheel_joint</driveJoint>
      <!-- <fixedWheelLeftJoint>base2fixed_left_wheel_joint</fixedWheelLeftJoint>
      <fixedWheelRightJoint>base2fixed_right_wheel_joint</fixedWheelRightJoint> -->

      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <steeringFixWheelDistanceX>1.190</steeringFixWheelDistanceX>
      <steeringFixWheelDistanceY>0.0</steeringFixWheelDistanceY>
      
      <steerTorque>1000</steerTorque>
      <driveTorque>1000</driveTorque>

      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>/world</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>

      <wheelAcceleration>0.5</wheelAcceleration>

      <odomEncSteeringAngleOffset>0.01</odomEncSteeringAngleOffset>
 
      <!--odometrySource>encoder</odometrySource-->
      
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

</robot>